name: 'Setup Node Frontend'
description: 'Setup Node.js environment for OmniPost frontend with caching'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20.x'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      shell: bash
      run: |
        echo "📦 Installing npm dependencies..."
        npm ci
