name: 'Setup Node.js Environment'
description: 'Setup Node.js with caching and install dependencies'

inputs:
  node-version:
    description: 'Node.js version to setup'
    required: false
    default: '18.x'
  install-deps:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: npm ci
