name: 'Setup Python Environment'
description: 'Setup Python with caching and install backend dependencies'

inputs:
  python-version:
    description: 'Python version to setup'
    required: false
    default: '3.10'
  install-deps:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'
  extras:
    description: 'Extras to install (e.g., "dev")'
    required: false
    default: ''
  install-playwright:
    description: 'Whether to install Playwright browsers'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: apps/backend/pyproject.toml
    
    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip
    
    - name: Install backend dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      working-directory: apps/backend
      run: |
        if [ -n "${{ inputs.extras }}" ]; then
          pip install -e ".[${{ inputs.extras }}]"
        else
          pip install -e .
        fi
    
    - name: Install Playwright browsers
      if: inputs.install-playwright == 'true'
      shell: bash
      run: python -m playwright install chromium
